version: 2
jobs:
  tests:
    machine:
      image: circleci/classic:201711-01
    working_directory: /tmp/tests
    steps:
      - checkout:
          path: /tmp/src/templateflow

      - run:
          name: Install git and git-annex
          command: |
            wget -O- http://neuro.debian.net/lists/trusty.us-ca.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
            sudo apt-key adv --recv-keys --keyserver hkp://pool.sks-keyservers.net:80 0xA5D32F012649A5A9
            sudo apt update && sudo apt-get install -y --no-install-recommends git-annex-standalone
            git config --global user.name "First Last"
            git config --global user.email "email@domain.com"

      - run:
          name: Run tests
          command: |
            pyenv global 3.5.2
            virtualenv venv
            pip install -r /tmp/src/templateflow/requirements.txt
            pytest -vsx --doctest-modules /tmp/src/templateflow/templateflow

      - run:
          name: Test packaging
          command: |
            pyenv global 3.5.2
            virtualenv venv
            pip install "setuptools>=27.0" twine
            cd /tmp/src/templateflow
            echo "${CIRCLE_TAG}" > templateflow/VERSION
            echo "include templateflow/VERSION" >> MANIFEST.in
            python setup.py check -r -s

  deploy_pypi:
    machine:
      image: circleci/classic:201711-01
    working_directory: /tmp/src/templateflow
    steps:
      - checkout:
          path: /tmp/src/templateflow
      - run:
          name: Deploy to PyPi
          command: |
            pyenv global 3.5.2
            virtualenv venv
            pip install "setuptools>=27.0" twine
            echo "${CIRCLE_TAG}" > templateflow/VERSION
            echo "include templateflow/VERSION" >> MANIFEST.in
            python setup.py check -r -s
            python setup.py sdist
            twine upload dist/*

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - tests:
          filters:
            tags:
              only: /.*/
      - deploy_pypi:
          requires:
            - tests
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
